plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace "com.zamuuk.godot.handtracking"
    compileSdk 35

    defaultConfig {
        minSdk 24
        targetSdk 35
    }
}

dependencies {
    implementation "org.godotengine:godot:4.4.1.stable"
    implementation "com.google.mediapipe:tasks-vision:latest.release"
    implementation "androidx.camera:camera-camera2:1.5.0"
    implementation "androidx.camera:camera-lifecycle:1.5.0"
    implementation "androidx.camera:camera-core:1.5.0"
}
